print('Qual o resultado de cruzar um cachorro com um gato?')
input()
print('Uma baita duma briga!')
print()
print('Qual a diferença entre Brasília e uma caixa d\'água?')
input()
print('Na caixa d\'água só tem um ladrão...')
print()
print('Toque toque!')
input()
print('Quem é?')
input()
print('A vaca interrompida!')
input()
print('Que vaca interromp-', end='')
print('MUUUUU!!')
